### ISSUE TITLE
[SurfaceVis] Improvements roadmap

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#1306]
Here are the envisioned features for the upcoming `SurfaceVis`: 

- [ ] Allow to change the domain and the color map
- [ ] Support of several scale types
- [ ] Display axes values
- [ ] Initialize the camera to show the full plot

The list may evolve with time.
