### ISSUE TITLE
Rethink domain slider UI

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#510]
The domain slider UI suffers from a few limitations:

- The values displayed in the thumbs sometimes don't match the actual values applied.
- The thumbs change size based on their values, which causes rendering issues with `ReactSlider`.
- The range is limited to +/-10% of the current dataset's domain (technically, the domain of the dataset that was selected when auto-scale was turned off -- see #486)
- We have no clue what the min/max values of the current dataset are.
- We can't auto-scale the min/max bounds individually from the other.
- We can't type in min/max bounds manually

To resolve these issues, we suggest the following interface:

### Mockups (v3.1)

![domain slider v3](https://user-images.githubusercontent.com/2936402/108857646-960b0100-75eb-11eb-941b-a62908fbf4d9.png)

<details>
![domain slider v2](https://user-images.githubusercontent.com/2936402/108846642-17a86200-75df-11eb-87d1-61e6f8a1bab5.png)

<summary>Previous versions</summary>
![image](https://user-images.githubusercontent.com/2936402/108386270-c843e980-720c-11eb-8335-6505b2e2d252.png)

![domain slider](https://user-images.githubusercontent.com/2936402/108715212-d51d5180-751a-11eb-9669-58f34f94a520.png)
</details>

### Specifications

- [x] The thumbs don't show values. #524 
- [x] The range of the slider is always an extension of the currently applied domain -- in other words, after clicking/dragging/releasing a thumb, it always comes back to its initial position and the thumbs never stay on top of each other, even when switching dataset with totally different data domains. #534 
  - [x] The only exception is if the two thumbs receive the same value. In this case, they end up in the middle of the slider, one on top of the other. #534 
- [x] If the data domain intersects with the range of the slider, the intersecting range is shown in dark on the slider's bar. #530 
- [x] When the slider is hovered, a popup appears that: #521
  - [x] shows the currently applied min/max bounds, as well as the min/max values of the data; #521
  - [x] allows entering custom min/max values (with an inline editing UI); #557 
  - [x] allows autoscaling the min/max bounds. #521
- ~The "Auto" toggle next to the slider toggles the autoscale of both bounds together, but if auto-scale is turned on or off for a specific bound from the popup, then the toggle shows "Auto (min)" or "Auto (max)". Clicking the toggle in this state turns auto-scale off for the corresponding bound.~
- [x] Moving a thumb or entering (and applying) a custom value for a bound turns autoscale off for this bound. #529 #557 
- [x] If a bound is given an invalid value (i.e. `min` greater than `max` or `max` lower than `min`), the value is saved, but the value that is actually used for the visualization and the domain slider is the value of the other bound (i.e. `min` = `max`). When this occurs, a warning message is shown below the bound and the corresponding slider thumb is highlighted in a noticeable colour. #538 #565 
- [x] A similar behaviour to the above occurs when a bound has a custom value that is lower than or equal to zero and the user switches to the log scale, in which case the data min (i.e. the smallest positive value in the data) and max are applied. #538 
  - [x] The data domain should fall back to `[0.1, 1]` when the scale is log and the data contains only negative values (`[-x, -y]` or `[-x, 0]` to be exact). #538 
- [x] When the user switch to the log scale, the domain slider must also use a log scale. #534 
- ~When the user moves the mouse out of the popup and the popup disappears, any internal edit state must be maintained.~
- [x] The user can edit both min and max at the same time. #557 
- [x] If a thumb is moved or the data domain changes (e.g change of scale) while the user is editing min and/or max, the editing is automatically cancelled. #557 

### v3.2

- [x] The "Auto" toggle is replaced with an "Edit" toggle. #557 
  - [x] Pressing it opens (i.e. "pins") the tooltip and turns editing on for both min and max. #557 
  - [x] Depressing it unpins the tooltip and cancels editing for both min and max. #557 
- [x] ~Clicking on~ Focusing the input field for min or max ~(or on the pencil buttons)~ in the hover-triggered tooltip "pins" the tooltip and turns editing on but only for the bound that was clicked. #557 
- [x] Applying a new value to a bound turns editing off for this bound but does not unpin the tooltip if the other bound is still being edited. #557 

### v3.3

- ~Show the "requested" domain in the slider rather than the "valid" domain (e.g. display the min thumb on the far left when the custom min is negative and the scale is log).~
- [x] When a bound is invalid, show the invalid value in the tooltip, not the valid value. #557 
- [x] When an error message disappears (e.g. by auto-scaling min or max), do not shrink the tooltip or move the auto-scale buttons until the popup is closed.  #560

### v3.4

- [x] The tooltip contains input fields for min and max even when not in editing mode. Editing mode is turned on for a bound by giving focus to a field (or pinning the tooltip). When editing mode is enabled for a bound, the input field is highlighted and the apply/cancel buttons are enabled. #557

**Comment by t20100** [comment]
A few quick feedbacks:
- It is nice to display the extent of the data in the range slide, and to separate min/max autoscale.
- The `min` and `max` values are duplicated between the display and edit area. To me it seems you can combine both areas, and spare the "Apply" buttons (press enter or loose focus would do the job); remove the "Cancel" buttons (or turn them into "undo" buttons). Something like:

  <img src="https://user-images.githubusercontent.com/9449698/108730199-95ab3100-752b-11eb-92ac-b0e8fda7c79a.png"  width="200">
   ... except for erroneous cases.

- Maybe display error as a tooltip and indicate erroneous value by displaying the value in red or with an icon to avoid the component to change size.
- In case max < min, I would just change the values to avoid this situation.

Option (not for now I guess!): display the histogram of the data either as a histogram (https://github.com/airbnb/rheostat#rheostat) or with a colormap to be more compact (see http://www.silx.org/doc/silx/latest/modules/gui/widgets/rangeslider.html).

**Comment by axelboc** [comment]
Mockups and specifications edited as per our discussion.

**Comment by axelboc** [comment]
### Roadmap

- [ ] Implement basic popup on hover (non-editable min/max, data min/max, working auto-scale buttons) and remove values from thumbs.
- [ ] Manage range of slider (always +/- 10% extension of applied domain, log range).
- [ ] Handle invalid custom min/max (error message and fallback behaviour).
- [ ] Editing of custom min/max (edit/save/cancel, turn off auto-scale on save, cancel editing when thumbs are moved or data domain changes).
- [ ] Highlight data domain on slider.

**Comment by axelboc** [comment]
### Handling of min > max

The user can enter a `min` value greater than the `max` value or vice versa. The current behaviour when this happens is actually quite interesting: the colour map is basically inverted!

![image](https://user-images.githubusercontent.com/2936402/110927986-a37ff500-8326-11eb-9a59-fe089fb10408.png)

- The slider continues to work; the only difference is that it is reversed: moving a thumb to the left increases its value instead of decreasing it, and vice versa.
- One thing that is broken is the display of the data domain on the slider's track.
- The user can flip the bounds back by modifying the values manually or by bring the two thumbs together and separating them again.

This behaviour doesn't actually seem "wrong". We could just:

- [ ] fix the display of the data domain on the  track;
- [ ] show the warning icon on both thumbs;
- [ ] display a warning at the top of the tooltip such as "Min greater than max"; and
- [ ] provide a button next to the warning to swap the bounds back.
