### ISSUE TITLE
Improve fetching for large datasets

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#616]
Having played around with large datasets (~10M of points but a slice is ~100k), I find that the long fetch of the data breaks the flow... 

Let's make use of this issue to gather possible improvements:
- [ ] Allow the user to cancel requests
- [ ] Request domain separately to avoid computing in the front-end
- [ ] Make use of binary instead of JSON
- [ ] Implement specific strategies for fetching of large datasets (e.g. use subsampling; warn the user that the fetching can take a long time and ask them if they want to proceed anyway...)

**Comment by axelboc** [comment]
I'd add that, when performing long downloads and computations, the UI should:

- be more informative (i.e. progress status, subsampling rate, etc.)
- remain responsive and allow cancelling slow computations (i.e. not just requests)

**Comment by loichuder** [comment]
Our discussion on https://github.com/silx-kit/h5web/pull/632 also gave me an idea: we could make the flattening operation more consistent by encapsulating in the `get/useValue` method. 

It then becomes relevant to this issue as it would be a stepping stone to request the flattening on the back-end. Thus, avoiding another expensive computation in h5web.

**Comment by axelboc** [comment]
In the providers' `getValue()` methods? Yeah, totally 👍

**Comment by axelboc** [comment]
#635 implements cancellation on the front-end, but it doesn't resolve crashes on Bosquet when attempting to fetch (and cancel the fetch of) extremely large datasets.

**Comment by axelboc** [comment]
#640 implements retrying after cancelling (including evicting cancellation errors from the value store's cache).

**Comment by jreadey** [comment]
Just curious - for HSDS, have you tried using HTTP Compression?  That should reduce the payload size considerably.

**Comment by loichuder** [comment]
Unfortunately, the impact will be limited as most of our heavy datasets are not compatible with HSDS due to https://github.com/HDFGroup/hsds/issues/76 :confused: 

But this is something that we still need to try !

**Comment by loichuder** [comment]
The auto-scale feature in the `LineVis` that forces us to fetch the whole dataset can be a real limiter for huge datasets (https://github.com/silx-kit/jupyterlab-h5web/issues/71). 

Maybe, it is time to review it ? We could
- Disable it somehow for huge datasets. And give an indication to the user ?
- Request the domain separately (as proposed originally in https://github.com/silx-kit/h5web/issues/616#issue-862920494) to avoid the need to compute it in the front-end (and therefore the need to have the full dataset values)

**Comment by headtr1ck** [comment]
It seems that h5wasm now (as of v0.4.8) supports lazy loading of arrays.
Is that beneficial for this issue as well (or in general for loading files >2GB)?
Not really familiar with the interal workings though, so excuse me if this has nothing to do with this :)

For reference, see this discussion: https://github.com/usnistgov/h5wasm/issues/40

**Comment by loichuder** [comment]
Sure, that's relevant also for large datasets. 

For h5wasm, we have a more specific issue tracking this at https://github.com/silx-kit/h5web/issues/1264

**Comment by domna** [comment]
Is it also planned to have streaming binary support for hsds?
I could also try to implement it myself in the hsds api but I'm not a typescript expert, so I could use some guidance.

I experienced problems with this while I was experimenting with storing and loading large datasets via hsds and I use h5web in a simple hsds directory browser to view the stored data. However, the hsds server gets stuck on large datasets because h5web requests the data in json format.

**Comment by loichuder** [comment]
> Is it also planned to have streaming binary support for hsds? I could also try to implement it myself in the hsds api but I'm not a typescript expert, so I could use some guidance.

To be honest, we don't really plan to improve the HSDS part since we mostly use h5grove and h5wasm. But you are welcome to contribute and we will be happy to help you doing so.

If you have some working code, feel free to open a draft PR to discuss. If something blocks you, you can drop us a line at `h5web@esrf.fr`.
